import { useState } from 'react'
import type { Meta } from '@storybook/react-vite'
import { ArrowRight, MoreHorizontal, Plus } from 'lucide-react'
import { Badge, Button, Dialog, Dropdown, DropdownItem, Field, IconButton, Input, PageHeader, Surface, Tooltip } from '../design-system/components'

const meta = { title: 'GLL Design System/Components' } satisfies Meta
export default meta

export const Buttons = { render: () => <main className="gll-surface"><h1>Ações</h1><div className="gll-ds-row"><Button><Plus size={16}/> Primária</Button><Button variant="secondary">Secundária</Button><Button variant="quiet">Discreta</Button><Button variant="danger">Destrutiva</Button><Button disabled>Desabilitada</Button><IconButton label="Mais opções"><MoreHorizontal size={18}/></IconButton></div></main> }
export const ButtonPlayground = { args: { label: 'Salvar edital', variant: 'primary', disabled: false }, argTypes: { label: { control: 'text' }, variant: { control: 'select', options: ['primary', 'secondary', 'quiet', 'danger'] }, disabled: { control: 'boolean' } }, render: ({ label, variant, disabled }: { label: string; variant: 'primary' | 'secondary' | 'quiet' | 'danger'; disabled: boolean }) => <Button variant={variant} disabled={disabled}>{label}</Button> }
export const FormFields = { render: () => <main className="gll-surface"><h1>Campos de formulário</h1><div className="gll-form-grid"><Field htmlFor="story-name" label="Órgão comprador" required hint="Informe o nome oficial."><Input id="story-name" placeholder="Município de..."/></Field><Field htmlFor="story-number" label="Número do edital" required error="Já existe um edital com este número."><Input id="story-number" aria-invalid="true" defaultValue="PE 014/2026"/></Field><Field htmlFor="story-select" label="Modalidade"><select id="story-select" className="gll-input"><option>Pregão eletrônico</option><option>Concorrência</option></select></Field><Field htmlFor="story-disabled" label="Desabilitado"><Input id="story-disabled" disabled value="Indisponível" readOnly/></Field></div></main> }
export const Badges = { render: () => <main className="gll-surface"><h1>Estados</h1><div className="gll-ds-row"><Badge>Neutro</Badge><Badge tone="success">Aprovada</Badge><Badge tone="warning">Em análise</Badge><Badge tone="danger">Desclassificado</Badge><Badge tone="info">Disputada</Badge></div></main> }
export const Feedback = { render: () => <main className="gll-surface"><h1>Feedback</h1><div className="gll-inline-alert"><ArrowRight size={18}/><div><strong>Informação operacional</strong><p>Uma mensagem sempre comunica a próxima ação.</p></div></div><div className="gll-empty"><div className="gll-empty-icon"><Plus size={20}/></div><h3>Nenhum registro</h3><p>Cadastre o primeiro item para começar.</p><Button>Adicionar item</Button></div></main> }
function DialogStory() { const [open, setOpen] = useState(false); return <main className="gll-surface"><h1>Diálogo</h1><Button onClick={() => setOpen(true)}>Abrir diálogo</Button><Dialog open={open} onOpenChange={setOpen} title="Confirmar alteração?" description="Revise os dados antes de continuar." footer={<><Button variant="quiet" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={() => setOpen(false)}>Confirmar</Button></>}><Field htmlFor="story-dialog-name" label="Nome"><Input id="story-dialog-name" placeholder="Digite um nome"/></Field></Dialog></main> }
export const Dialogs = { render: () => <DialogStory/> }
export const MenusAndTooltips = { render: () => <main className="gll-surface"><h1>Dropdown e tooltip</h1><div className="gll-ds-row"><Dropdown trigger={<Button variant="secondary">Opções <MoreHorizontal size={16}/></Button>}><DropdownItem className="gll-dropdown-item">Visualizar</DropdownItem><DropdownItem className="gll-dropdown-item">Editar</DropdownItem></Dropdown><Tooltip label="Informação contextual"><IconButton label="Ajuda"><MoreHorizontal size={18}/></IconButton></Tooltip></div></main> }
export const Surfaces = { render: () => <main style={{ maxWidth: 560 }}><Surface><PageHeader kicker="GESTÃO / EDITAIS" title="Licitações" description="Acompanhe editais e decisões." actions={<Button>Novo edital</Button>}/><p className="gll-muted">A superfície define borda, elevação e espaçamento de conteúdo.</p></Surface></main> }
