import { useState } from 'react'
import type { Meta } from '@storybook/react-vite'
import { ArrowRight, MoreHorizontal, Plus } from '../design-system/icons'
import { Alert, Badge, Button, Checkbox, Dialog, Dropdown, DropdownItem, EmptyState, Field, IconButton, Input, Loading, PageHeader, Radio, Select, Skeleton, StatusBadge, Surface, Switch, Tag, Textarea, Toast, Tooltip } from '../design-system/components'

const meta = { title: 'GLL Design System/Components' } satisfies Meta
export default meta

export const Buttons = { render: () => <main className="gll-surface"><h1>Ações</h1><div className="gll-ds-row"><Button><Plus size={16}/> Primária</Button><Button variant="secondary">Secundária</Button><Button variant="quiet">Discreta</Button><Button variant="danger">Destrutiva</Button><Button disabled>Desabilitada</Button><IconButton label="Mais opções"><MoreHorizontal size={18}/></IconButton></div></main> }
export const ButtonPlayground = { args: { label: 'Salvar edital', variant: 'primary', disabled: false }, argTypes: { label: { control: 'text' }, variant: { control: 'select', options: ['primary', 'secondary', 'quiet', 'danger'] }, disabled: { control: 'boolean' } }, render: ({ label, variant, disabled }: { label: string; variant: 'primary' | 'secondary' | 'quiet' | 'danger'; disabled: boolean }) => <Button variant={variant} disabled={disabled}>{label}</Button> }
export const FormFields = { render: () => <main className="gll-surface"><h1>Campos de formulário</h1><div className="gll-form-grid"><Field htmlFor="story-name" label="Órgão comprador" required hint="Informe o nome oficial."><Input id="story-name" placeholder="Município de..."/></Field><Field htmlFor="story-number" label="Número do edital" required error="Já existe um edital com este número."><Input id="story-number" aria-invalid="true" defaultValue="PE 014/2026"/></Field><Field htmlFor="story-select" label="Modalidade"><select id="story-select" className="gll-input"><option>Pregão eletrônico</option><option>Concorrência</option></select></Field><Field htmlFor="story-disabled" label="Desabilitado"><Input id="story-disabled" disabled value="Indisponível" readOnly/></Field></div></main> }
export const Badges = { render: () => <main className="gll-surface"><h1>Estados</h1><div className="gll-ds-row"><Badge>Neutro</Badge><Badge tone="success">Aprovada</Badge><Badge tone="warning">Em análise</Badge><Badge tone="danger">Desclassificado</Badge><Badge tone="info">Disputada</Badge></div></main> }
export const Feedback = { render: () => <main className="gll-surface"><h1>Feedback</h1><div className="gll-inline-alert"><ArrowRight size={18}/><div><strong>Informação operacional</strong><p>Uma mensagem sempre comunica a próxima ação.</p></div></div><div className="gll-empty"><div className="gll-empty-icon"><Plus size={20}/></div><h3>Nenhum registro</h3><p>Cadastre o primeiro item para começar.</p><Button>Adicionar item</Button></div></main> }
function DialogStory() { const [open, setOpen] = useState(false); return <main className="gll-surface"><h1>Diálogo</h1><Button onClick={() => setOpen(true)}>Abrir diálogo</Button><Dialog open={open} onOpenChange={setOpen} title="Confirmar alteração?" description="Revise os dados antes de continuar." footer={<><Button variant="quiet" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={() => setOpen(false)}>Confirmar</Button></>}><Field htmlFor="story-dialog-name" label="Nome"><Input id="story-dialog-name" placeholder="Digite um nome"/></Field></Dialog></main> }
export const Dialogs = { render: () => <DialogStory/> }
export const MenusAndTooltips = { render: () => <main className="gll-surface"><h1>Dropdown e tooltip</h1><div className="gll-ds-row"><Dropdown trigger={<Button variant="secondary">Opções <MoreHorizontal size={16}/></Button>}><DropdownItem className="gll-dropdown-item">Visualizar</DropdownItem><DropdownItem className="gll-dropdown-item">Editar</DropdownItem></Dropdown><Tooltip label="Informação contextual"><IconButton label="Ajuda"><MoreHorizontal size={18}/></IconButton></Tooltip></div></main> }
export const Surfaces = { render: () => <main style={{ maxWidth: 560 }}><Surface><PageHeader kicker="GESTÃO / EDITAIS" title="Licitações" description="Acompanhe editais e decisões." actions={<Button>Novo edital</Button>}/><p className="gll-muted">A superfície define borda, elevação e espaçamento de conteúdo.</p></Surface></main> }
export const TextareaAndSelect = { render: () => <main className="gll-surface" style={{ maxWidth: 650 }}><h1>Seleção e texto longo</h1><div className="gll-form-grid"><Field htmlFor="story-select-official" label="Modalidade"><Select id="story-select-official"><option>Pregão eletrônico</option><option>Concorrência</option></Select></Field><Field htmlFor="story-notes" label="Observações" hint="Até 500 caracteres."><Textarea id="story-notes" rows={3} placeholder="Registre informações relevantes"/></Field></div></main> }
function ChoicesStory() { const [checked, setChecked] = useState(true); const [choice, setChoice] = useState('pregao'); const [enabled, setEnabled] = useState(false); return <main className="gll-surface"><h1>Controles de escolha</h1><div className="gll-ds-row"><Checkbox id="story-checkbox" label="Item incluído" checked={checked} onCheckedChange={setChecked}/><Radio name="story-modality" value="pregao" label="Pregão" checked={choice === 'pregao'} onChange={setChoice}/><Radio name="story-modality" value="concorrencia" label="Concorrência" checked={choice === 'concorrencia'} onChange={setChoice}/><Switch label="Notificações" checked={enabled} onChange={setEnabled}/></div></main> }
export const Choices = { render: () => <ChoicesStory/> }
export const StatusAndTags = { render: () => <main className="gll-surface"><h1>Status e tags</h1><div className="gll-ds-row">{['Em análise', 'Disputada', 'Aprovada', 'Faturado', 'Descartada', 'Desclassificado'].map((status) => <StatusBadge key={status} status={status}/>)}<Tag>Tecnologia</Tag></div></main> }
export const Alerts = { render: () => <main className="gll-surface" style={{ display: 'grid', gap: 12 }}><h1>Alertas</h1><Alert title="Informação">Os dados foram atualizados.</Alert><Alert title="Revise os documentos" tone="warning">Há documentos pendentes no edital.</Alert><Alert title="Não foi possível salvar" tone="danger">Confira os campos indicados.</Alert><Alert title="Concluído" tone="success">O edital foi salvo.</Alert></main> }
export const EmptyAndLoading = { render: () => <main className="gll-surface"><h1>Estados de conteúdo</h1><EmptyState title="Nenhum registro encontrado" description="Ajuste os filtros ou cadastre um novo item." action={<Button>Novo item</Button>}/><div className="gll-ds-row"><Loading/><Skeleton width="120px"/><Skeleton width="220px"/></div></main> }
function ToastStory() { const [show, setShow] = useState(false); return <main className="gll-surface"><h1>Toast</h1><Button onClick={() => setShow(true)}>Mostrar mensagem</Button>{show && <Toast message="Edital salvo no protótipo." onDismiss={() => setShow(false)}/>}</main> }
export const Toasts = { render: () => <ToastStory/> }
