import { useState, type FormEvent } from 'react'
import { Button, Dialog, EmptyState, Field, Input, Surface, Textarea } from '../design-system/components'
import { Download, Plus } from '../design-system/icons'
import { money, type Bid, type BidItem, type Budget } from '../data/demo'

type Draft = { number: string; description: string; model: string; manufacturer: string; technicalText: string; quantity: string; estimatedValue: string; cost: string; finalValue: string; minimumBid: string; won: boolean; suppliers: string[]; specifications: { name: string; value: string }[] }
const emptyDraft = (): Draft => ({ number: '', description: '', model: '', manufacturer: '', technicalText: '', quantity: '1', estimatedValue: '', cost: '', finalValue: '', minimumBid: '', won: false, suppliers: [], specifications: [] })
const toDraft = (item: BidItem): Draft => ({ number: String(item.number), description: item.description, model: item.model ?? '', manufacturer: item.manufacturer ?? '', technicalText: item.technicalText ?? '', quantity: String(item.quantity), estimatedValue: item.estimatedValue ? String(item.estimatedValue) : '', cost: item.cost ? String(item.cost) : '', finalValue: item.finalValue ? String(item.finalValue) : '', minimumBid: item.minimumBid ? String(item.minimumBid) : '', won: item.won, suppliers: item.suppliers ?? [], specifications: item.specifications ?? [] })
const uid = () => `item-${crypto.randomUUID()}`
const numeric = (value: string) => value === '' ? 0 : Number(value)
const csvCell = (value: string | number) => `"${String(value).replaceAll('"', '""').replace(/^([=+\-@])/, "'$1")}"`

export function QuotationItemsPanel({ bid, linkedBudget, onPatch, onFind, onCreate, onNotify, readOnly }: { bid: Bid; linkedBudget?: Budget; onPatch: (id: string, patch: Partial<Bid>) => void; onFind: () => void; onCreate: () => void; onNotify: (message: string) => void; readOnly: boolean }) {
  const items = bid.items ?? []
  const [open, setOpen] = useState(false)
  const [discardOpen, setDiscardOpen] = useState(false)
  const [dirty, setDirty] = useState(false)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [draft, setDraft] = useState<Draft>(emptyDraft)
  const [supplierInput, setSupplierInput] = useState('')
  const [specName, setSpecName] = useState('')
  const [specValue, setSpecValue] = useState('')
  const [margin, setMargin] = useState('')
  const [error, setError] = useState('')
  const change = <K extends keyof Draft>(key: K, value: Draft[K]) => { setDraft((current) => ({ ...current, [key]: value })); setDirty(true) }
  const clear = () => { setSelectedId(null); setDraft(emptyDraft()); setSupplierInput(''); setSpecName(''); setSpecValue(''); setMargin(''); setError(''); setDirty(false) }
  const start = (item?: BidItem) => { clear(); if (item) { setSelectedId(item.id); setDraft(toDraft(item)) } setOpen(true) }
  const requestClose = (next: boolean) => { if (next) { setOpen(true); return } if (dirty) setDiscardOpen(true); else setOpen(false) }
  const total = numeric(draft.finalValue) * numeric(draft.quantity)
  const profit = (numeric(draft.finalValue) - numeric(draft.cost)) * numeric(draft.quantity)
  const marginValue = numeric(draft.cost) * (1 + numeric(margin) / 100)
  const canMarkWon = ['Aprovada', 'Faturado', 'Desclassificado', 'Disputada'].includes(bid.status)
  const save = (event: FormEvent) => {
    event.preventDefault()
    const number = Number(draft.number)
    const quantity = Number(draft.quantity)
    const values = [draft.estimatedValue, draft.cost, draft.finalValue, draft.minimumBid].filter(Boolean).map(Number)
    if (!Number.isInteger(number) || number < 0 || !Number.isFinite(quantity) || quantity <= 0 || values.some((value) => !Number.isFinite(value) || value < 0)) { setError('Confira o número, a quantidade e os valores do item.'); return }
    if (items.some((item) => item.number === number && item.id !== selectedId)) { setError('Já existe um item com esse número.'); return }
    const next: BidItem = { id: selectedId ?? uid(), number, description: draft.description.trim(), model: draft.model.trim(), manufacturer: draft.manufacturer.trim(), technicalText: draft.technicalText.trim(), quantity, estimatedValue: numeric(draft.estimatedValue), cost: numeric(draft.cost), finalValue: numeric(draft.finalValue), minimumBid: numeric(draft.minimumBid), won: canMarkWon && draft.won, suppliers: draft.suppliers, specifications: draft.specifications }
    onPatch(bid.id, { items: selectedId ? items.map((item) => item.id === selectedId ? next : item) : [...items, next] })
    setOpen(false); clear(); onNotify('Item do orçamento salvo no protótipo.')
  }
  const download = () => {
    const rows = ['Item;Descrição;Modelo;Fabricante;Estimado;Custo;Lance final;Lance mínimo;Quantidade;Total;Lucro;Vencido', ...items.map((item) => [item.number, item.description, item.model ?? '', item.manufacturer ?? '', item.estimatedValue ?? 0, item.cost, item.finalValue, item.minimumBid ?? 0, item.quantity, item.quantity * item.finalValue, item.quantity * (item.finalValue - item.cost), item.won ? 'Sim' : 'Não'].map(csvCell).join(';'))]
    const url = URL.createObjectURL(new Blob(['\ufeff', rows.join('\r\n')], { type: 'text/csv;charset=utf-8' }))
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = `itens-${bid.edital.replace(/[^a-z0-9-]/gi, '-')}.csv`; anchor.click()
    window.setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
  return <>
    <Surface className="gll-bid-panel"><div className="gll-bid-panel-head"><div><span className="gll-kicker">ORÇAMENTO VINCULADO</span><h2>{linkedBudget ? `${linkedBudget.id} · ${linkedBudget.title}` : 'Nenhum orçamento vinculado'}</h2><p>{linkedBudget ? `${linkedBudget.agency} · ${linkedBudget.items} itens · ${money(linkedBudget.total)}` : 'Vincule um orçamento já cadastrado ou crie um novo para este edital.'}</p></div><div><Button variant="secondary" disabled={readOnly} onClick={onFind}>{linkedBudget ? 'Trocar orçamento' : 'Vincular orçamento'}</Button><Button disabled={readOnly} onClick={onCreate}><Plus size={16} /> Criar novo orçamento</Button></div></div></Surface>
    {(linkedBudget || bid.quotationId) && <Surface className="gll-bid-panel"><div className="gll-bid-panel-head"><div><h2>Itens do edital</h2><p>Revise custos, lances e quantidades do orçamento vinculado.</p></div><div><Button variant="quiet" size="small" disabled={!items.length} onClick={download}><Download size={16} /> Baixar itens</Button><Button disabled={readOnly} onClick={() => start()}><Plus size={16} /> Cadastrar item</Button></div></div>{items.length ? <div className="gll-table-scroll"><table className="gll-bid-subtable"><thead><tr><th>Item</th><th>Descrição / modelo</th><th>Marca / fabricante</th><th>Estimado</th><th>Custo</th><th>Lance final</th><th>Mínimo</th><th>Quantidade</th><th>Total</th><th>Lucro</th>{canMarkWon && <th>Vencido</th>}</tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><button className="gll-text-link" onClick={() => start(item)} aria-label={`Abrir item ${item.number}`}>{item.number}</button></td><td>{item.description || 'Sem descrição'}{item.model && <small>{item.model}</small>}</td><td>{item.manufacturer || '—'}</td><td>{money(item.estimatedValue ?? 0)}</td><td>{money(item.cost)}</td><td>{money(item.finalValue)}</td><td>{money(item.minimumBid ?? 0)}</td><td>{item.quantity}</td><td>{money(item.quantity * item.finalValue)}</td><td>{money(item.quantity * (item.finalValue - item.cost))}</td>{canMarkWon && <td>{item.won ? 'Sim' : 'Não'}</td>}</tr>)}</tbody></table></div> : <EmptyState title="Nenhum item cadastrado" description="Cadastre o primeiro item para compor os valores do edital." />}</Surface>}
    <Dialog open={open} onOpenChange={requestClose} className="gll-item-dialog" title={selectedId ? 'Editar item' : 'Cadastrar item'} description="Dados técnicos e valores do orçamento fictício."><form onSubmit={save} className="gll-item-form"><div className="gll-bid-form-grid"><Field htmlFor="item-number" label="Item" required><Input id="item-number" type="number" min="0" step="1" required disabled={readOnly} value={draft.number} onChange={(event) => change('number', event.target.value)} /></Field><Field htmlFor="item-description" label="Descrição"><Input id="item-description" disabled={readOnly} value={draft.description} onChange={(event) => change('description', event.target.value)} /></Field><Field htmlFor="item-model" label="Modelo"><Input id="item-model" disabled={readOnly} value={draft.model} onChange={(event) => change('model', event.target.value)} /></Field><Field htmlFor="item-manufacturer" label="Marca / Fabricante"><Input id="item-manufacturer" disabled={readOnly} value={draft.manufacturer} onChange={(event) => change('manufacturer', event.target.value)} /></Field><div className="gll-bid-wide"><Field htmlFor="item-technical" label="Texto Técnico"><Textarea id="item-technical" rows={2} disabled={readOnly} value={draft.technicalText} onChange={(event) => change('technicalText', event.target.value)} /></Field></div></div>
      <div className="gll-item-add-group"><strong>Links de fornecedores</strong><div><Input value={supplierInput} disabled={readOnly} onChange={(event) => setSupplierInput(event.target.value)} placeholder="Link ou nome do fornecedor" aria-label="Link do fornecedor" /><Button type="button" variant="secondary" disabled={readOnly || !supplierInput.trim()} onClick={() => { change('suppliers', [...draft.suppliers, supplierInput.trim()]); setSupplierInput('') }}>Cadastrar</Button></div><ul>{draft.suppliers.map((supplier, index) => <li key={`${supplier}-${index}`}>{supplier}<Button type="button" size="small" variant="quiet" disabled={readOnly} onClick={() => change('suppliers', draft.suppliers.filter((_, position) => position !== index))}>Remover</Button></li>)}</ul></div>
      <div className="gll-item-add-group"><strong>Especificações técnicas</strong><div><Input value={specName} disabled={readOnly} onChange={(event) => setSpecName(event.target.value)} placeholder="Característica" aria-label="Característica técnica" /><Input value={specValue} disabled={readOnly} onChange={(event) => setSpecValue(event.target.value)} placeholder="Valor" aria-label="Valor da característica" /><Button type="button" variant="secondary" disabled={readOnly || !specName.trim() || !specValue.trim()} onClick={() => { change('specifications', [...draft.specifications, { name: specName.trim(), value: specValue.trim() }]); setSpecName(''); setSpecValue('') }}>Adicionar</Button></div><ul>{draft.specifications.map((spec, index) => <li key={`${spec.name}-${index}`}><strong>{spec.name}:</strong> {spec.value}<Button type="button" size="small" variant="quiet" disabled={readOnly} onClick={() => change('specifications', draft.specifications.filter((_, position) => position !== index))}>Remover</Button></li>)}</ul></div>
      <h3>Valores do item</h3><div className="gll-bid-form-grid"><Field htmlFor="item-estimated" label="Valor estimado"><Input id="item-estimated" type="number" min="0" step="0.01" disabled={readOnly} value={draft.estimatedValue} onChange={(event) => change('estimatedValue', event.target.value)} /></Field><Field htmlFor="item-cost" label="Valor de custo"><Input id="item-cost" type="number" min="0" step="0.01" disabled={readOnly} value={draft.cost} onChange={(event) => change('cost', event.target.value)} /></Field><Field htmlFor="item-final" label="Lance final"><Input id="item-final" type="number" min="0" step="0.01" disabled={readOnly} value={draft.finalValue} onChange={(event) => change('finalValue', event.target.value)} /></Field><Field htmlFor="item-minimum" label="Lance mínimo"><Input id="item-minimum" type="number" min="0" step="0.01" disabled={readOnly} value={draft.minimumBid} onChange={(event) => change('minimumBid', event.target.value)} /></Field><Field htmlFor="item-quantity" label="Quantidade"><Input id="item-quantity" type="number" min="0.0001" step="any" disabled={readOnly} value={draft.quantity} onChange={(event) => change('quantity', event.target.value)} /></Field><Field htmlFor="item-total" label="Total" hint="Lance final × quantidade"><Input id="item-total" readOnly value={money(total)} /></Field><Field htmlFor="item-profit" label="Lucro total" hint="(Lance final − custo) × quantidade"><Input id="item-profit" readOnly value={money(profit)} /></Field>{canMarkWon && <label className="gll-bid-check"><input type="checkbox" checked={draft.won} disabled={readOnly} onChange={(event) => change('won', event.target.checked)} /><span>Item vencido</span></label>}</div>
      <div className="gll-item-margin"><div><strong>Calculadora de margem</strong><p>Simulação com base no custo; não altera o lance final.</p></div><Field htmlFor="item-margin" label="Margem (%)"><Input id="item-margin" type="number" step="0.0001" disabled={readOnly} value={margin} onChange={(event) => setMargin(event.target.value)} /></Field><Field htmlFor="item-margin-value" label="Valor com margem"><Input id="item-margin-value" readOnly value={margin && draft.cost ? money(marginValue) : ''} /></Field></div>
      {error && <p className="gll-error" role="alert">{error}</p>}<div className="gll-bid-editor-actions">{selectedId && !readOnly && <Button type="button" variant="danger" onClick={() => { onPatch(bid.id, { items: items.filter((item) => item.id !== selectedId) }); setOpen(false); clear(); onNotify('Item excluído do orçamento.') }}>Excluir item</Button>}<span /><Button type="button" variant="quiet" onClick={clear} disabled={readOnly}>Limpar</Button><Button type="submit" disabled={readOnly}>{selectedId ? 'Salvar alterações' : 'Cadastrar'}</Button></div></form></Dialog>
    <Dialog open={discardOpen} onOpenChange={setDiscardOpen} title="Descartar alterações?" description="Existem alterações não cadastradas neste item."><div className="gll-bid-editor-actions"><Button variant="quiet" onClick={() => setDiscardOpen(false)}>Continuar editando</Button><Button variant="danger" onClick={() => { setDiscardOpen(false); setOpen(false); clear() }}>Descartar alterações</Button></div></Dialog>
  </>
}
